# Generated by Django 3.1.2 on 2020-11-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0008_auto_20201108_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='integral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral_number', models.PositiveIntegerField(default=0, verbose_name='积分')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户信息表')),
            ],
        ),
        migrations.CreateModel(
            name='goods_special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferential_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='特价')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品信息外键')),
            ],
        ),
    ]
