# Generated by Django 3.1.2 on 2020-11-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20201108_2305'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_special',
            name='goods_preferential',
            field=models.IntegerField(choices=[(0, '无优惠'), (1, '特价优惠')], default=0, verbose_name='优惠方式'),
        ),
        migrations.AlterField(
            model_name='goods_special',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', unique=True, verbose_name='商品信息外键'),
        ),
    ]
