# Generated by Django 3.1.2 on 2020-11-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20201108_2305'),
        ('discounts', '0002_auto_20201109_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_special',
            name='goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品信息外键'),
        ),
    ]
