# Generated by Django 3.1.2 on 2020-11-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_auto_20201111_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integral',
            name='change_reason',
            field=models.IntegerField(choices=[(0, '推荐新用户'), (1, '推荐用户消费'), (2, '购买商品获取'), (3, '活动获取'), (4, '新用户注册'), (6, '购买商品消费'), (7, '退换货扣除积分'), (11, '不变化')], default=11, verbose_name='积分变化原因'),
        ),
    ]
