# Generated by Django 3.1.2 on 2020-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20201111_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='integral',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='积分增减时间'),
        ),
    ]
