# Generated by Django 3.1 on 2020-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_category',
            field=models.IntegerField(choices=[(0, '食品'), (1, '饮料'), (2, '调料'), (3, '化妆品'), (4, '手机卡'), (5, '外卖')], verbose_name='商品类别'),
        ),
    ]
