# Generated by Django 3.1 on 2020-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200828_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_image',
            field=models.ImageField(upload_to='goods/', verbose_name='商品图片'),
        ),
    ]
