# Generated by Django 3.1 on 2020-10-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20201007_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_category',
            field=models.IntegerField(choices=[(0, '食品'), (1, '饮料'), (2, '调料'), (3, '生活用品'), (4, '化妆品'), (5, '手机卡'), (6, '外卖')], verbose_name='商品类别'),
        ),
    ]
