# Generated by Django 3.1 on 2020-10-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20201008_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_preferential',
            field=models.IntegerField(choices=[(0, '无优惠'), (1, '特价优惠'), (2, '会员优惠'), (3, '优惠券优惠')], default=0, verbose_name='优惠方式'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_preferential_price',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=9, verbose_name='优惠价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='商品售价'),
        ),
    ]
