# Generated by Django 3.1.2 on 2020-11-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200828_1837'),
        ('goods', '0004_auto_20201011_2126'),
    ]

    operations = [
    ]
