# Generated by Django 3.1.2 on 2020-11-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_merge_20201106_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_preferential',
            field=models.IntegerField(choices=[(0, '无优惠'), (1, '特价优惠'), (2, '会员优惠'), (3, '优惠券优惠'), (4, '优惠券'), (5, '红包'), (6, '积分'), (7, '礼品卡')], default=0, verbose_name='优惠方式'),
        ),
    ]
