# Generated by Django 3.1.2 on 2020-11-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20201107_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_preferential',
            field=models.IntegerField(choices=[(0, '无优惠'), (1, '特价优惠'), (2, '会员优惠'), (3, '优惠券优惠'), (4, '红包优惠'), (5, '积分优惠'), (6, '礼品卡')], default=0, verbose_name='优惠方式'),
        ),
    ]
