# Generated by Django 3.1.2 on 2020-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20201107_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_preferential',
            field=models.IntegerField(choices=[(0, '无优惠'), (1, '特价优惠'), (2, '会员优惠'), (3, '优惠券优惠')], default=0, verbose_name='优惠方式'),
        ),
    ]
