# Generated by Django 3.1 on 2020-08-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=13, verbose_name='密码')),
                ('user_gender', models.CharField(max_length=4, verbose_name='性别')),
                ('user_number', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('user_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('user_creat_time', models.DateField(auto_now_add=True, verbose_name='用户创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=20, verbose_name='收件人姓名')),
                ('consignee_number', models.CharField(max_length=11, verbose_name='收件人手机号')),
                ('consignee_address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('consignee_default', models.BooleanField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户信息表')),
            ],
        ),
    ]
