# Generated by Django 3.1 on 2020-09-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=20, verbose_name='收件人姓名')),
                ('consignee_number', models.CharField(max_length=11, verbose_name='收件人手机号')),
                ('consignee_address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('consignee_default', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=256, verbose_name='密码')),
                ('user_gender', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('user_number', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('user_creat_time', models.DateField(auto_now_add=True, verbose_name='用户创建时间')),
                ('user_state', models.IntegerField(choices=[(0, '注销'), (1, '正常'), (2, '冻结')], default=1, verbose_name='用户状态')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付，待发货'), (2, '已发货，待收货'), (3, '已收货'), (4, '换货'), (5, '退货')], verbose_name='订单状态')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('payment_amount', models.FloatField(verbose_name='支付金额')),
                ('payment_method', models.IntegerField(choices=[(0, '现金支付'), (1, '微信支付'), (2, '支付宝支付')], verbose_name='支付方式')),
                ('payment_time', models.DateTimeField(verbose_name='支付时间')),
                ('expected_time', models.DateTimeField(verbose_name='期望配送时间')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.consignee', verbose_name='收货信息表')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品信息表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户信息表')),
            ],
        ),
        migrations.AddField(
            model_name='consignee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户信息表'),
        ),
    ]
