# Generated by Django 3.1 on 2020-09-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.AddField(
            model_name='order',
            name='goods_list',
            field=models.CharField(default='null', max_length=1024, verbose_name='商品列表'),
        ),
    ]
