# Generated by Django 3.1.2 on 2020-11-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_referrer',
            field=models.IntegerField(null=True, verbose_name='推荐人id'),
        ),
    ]
