# Generated by Django 3.1 on 2020-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200920_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_time',
            field=models.DateTimeField(blank=True, verbose_name='期望配送时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(blank=True, verbose_name='支付时间'),
        ),
    ]
