# Generated by Django 3.1 on 2020-08-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200820_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
