# Generated by Django 3.1 on 2020-09-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200922_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
