# Generated by Django 3.1 on 2020-09-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_super',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '超级用户')], default=0, verbose_name='是否为超级用户'),
        ),
    ]
