# Generated by Django 3.1 on 2020-09-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_user_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_super',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '后台管理用户')], default=0, verbose_name='是否为后台管理用户'),
        ),
    ]
