# Generated by Django 3.1 on 2020-09-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_json', models.JSONField(null=True, verbose_name='商品id和数量')),
                ('order_status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付，待发货'), (2, '已发货，待收货'), (3, '已收货'), (4, '换货'), (5, '退货')], verbose_name='订单状态')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('payment_amount', models.FloatField(verbose_name='支付金额')),
                ('payment_method', models.IntegerField(choices=[(0, '现金支付'), (1, '微信支付'), (2, '支付宝支付')], verbose_name='支付方式')),
                ('payment_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('expected_time', models.DateTimeField(null=True, verbose_name='期望配送时间')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.consignee', verbose_name='收货信息表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户信息表')),
            ],
        ),
    ]
