# Generated by Django 3.1 on 2020-09-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '待发货'), (2, '待收货'), (3, '已收货'), (4, '换货'), (5, '退货'), (6, '订单待取消'), (7, '订单已取消')], verbose_name='订单状态'),
        ),
    ]
