# Generated by Django 3.1.2 on 2020-11-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_consignee'),
        ('order', '0003_auto_20200928_0908'),
    ]

    operations = [
    ]
