# Generated by Django 3.1.2 on 2020-11-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_merge_20201106_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '待发货'), (2, '待收货'), (3, '已收货'), (4, '换货'), (9, '完成换货'), (5, '退货'), (10, '完成退货'), (6, '订单取消中'), (7, '订单已取消'), (8, '订单已删除')], verbose_name='订单状态'),
        ),
    ]
