# Generated by Django 3.1.2 on 2020-11-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_integral_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='integral_number',
            field=models.IntegerField(default=0, verbose_name='积分数量'),
        ),
    ]
