# Generated by Django 3.1.2 on 2020-11-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_integral_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='integral_use',
        ),
    ]
